'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestTimeUpdate
    
    '''<summary>
    '''txtProgramID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgramID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRevision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRevision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVersion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProgramName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgramName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProgramExec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgramExec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDevice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTemp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelete As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNewProgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewProgID As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEditTestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditTestTime As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvListing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvListing As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''mpePopupTestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''mpePopupTestTime_HF1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime_HF1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''mpePopupTestTime_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime_P1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mpePopupTestTime_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime_P2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnNewProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewProject As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNewProgID2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewProgID2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNextRev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextRev As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''popupTestTime_txtProgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtProgID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtRev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtRev As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtVer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtVer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtTesterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtTesterType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtProgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtProgName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtProgExec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtProgExec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtDevice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtTemp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtEffDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtSiteCount1TestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtSiteCount1TestTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtSiteCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtSiteCount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtOverhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtOverhead As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_btnCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_btnCalc As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rptSiteCountList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptSiteCountList As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''popupTestTime_btnInsertUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_btnInsertUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpePopupTestTime_DismissBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime_DismissBT As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''wucPopupInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wucPopupInfo As Global.CMAPP.Web.wucPopupInfo
End Class
