'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TestTimeUpdateV2
    
    '''<summary>
    '''txtProgramID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgramID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlRevision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRevision As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVersion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTester As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProgramName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgramName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProgramExec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProgramExec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDevice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTemp As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkMaxDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMaxDate As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMaxRev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMaxRev As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cblSiteCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblSiteCount As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnNewProgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewProgID As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtEditProgramID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditProgramID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditRevision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditRevision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditVersion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditTesterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditTesterType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditProgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditProgName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditProgExec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditProgExec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditDevice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditTemp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditEffDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''calEditEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calEditEffDate As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtEditSiteCount1TestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditSiteCount1TestTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditOverhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditOverhead As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnEditCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditCalculate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEditClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEditTestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditTestTime As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''wucPopupInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wucPopupInfo As Global.CMAPP.Web.wucPopupInfo
End Class
