'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wucCMAPPEdit
    
    '''<summary>
    '''ddlTestSiteEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTestSiteEdit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEditProgramID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditProgramID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditRevision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditRevision As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditVersion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditVersion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTesterEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTesterEdit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEditDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditDevice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlTempEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTempEdit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtEditProgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditProgName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditProgExec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditProgExec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditEffDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''calEditEffDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calEditEffDate As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''txtEditSiteCount1TestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditSiteCount1TestTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtEditOverhead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditOverhead As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnEditCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditCalculate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cblSiteCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblSiteCount As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''btnDuplicateTestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDuplicateTestTime As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEditClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEditTestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditTestTime As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnDeleteTestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteTestTime As Global.System.Web.UI.WebControls.Button
End Class
