'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wucTestTime
    
    '''<summary>
    '''mpePopupTestTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime As Global.AjaxControlToolkit.ModalPopupExtender
    
    '''<summary>
    '''mpePopupTestTime_HF1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime_HF1 As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''mpePopupTestTime_P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime_P1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''mpePopupTestTime_P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime_P2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''popupTestTime_txtProgID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtProgID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtRev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtRev As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtVer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtVer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtTesterType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtTesterType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtProgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtProgName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtProgExec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtProgExec As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtDevice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_txtTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_txtTemp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''popupTestTime_btnInsertUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupTestTime_btnInsertUpdate As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''mpePopupTestTime_DismissBT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpePopupTestTime_DismissBT As Global.System.Web.UI.WebControls.Button
End Class
